### ISSUE TITLE
Repo structure (contribution)

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/guide#12]
For people that want to contribute, we should document the different repositories and how they map to the overall architecture.

Example:

- **REST API**
    - `api` - the primary API for Screwdriver
    - `plugin-*` - HAPI plugins that validate/enforce input/output as well as authentication/authorization
    - `models` - Business logic between the Datastore and Execution Layer
    - `data-schema` - Definitions of the internal data structure

- **Web UI**
    - `ui`

- **Launcher**
    - `job-tools` - docker container with the self-contained screwdriver launcher
    - `launcher-execute` - cli to execute `screwdriver.yaml` steps

- **Execution Engine**
    - `executor-*`

- **Datastore**
    - `datastore-*`

- **Shared**
    - `config-parser` - Tool to parse the `screwdriver.yaml`

**Comment by stjohnjohnson** [comment]
What's interesting, is how simple kubernetes org is laid out (https://github.com/kubernetes/)
 - kubernetes - pretty much everything
 - kubernetes.github.io - documentation
 - dashboard - ui
 - contrib - generic bucket of stuff
 - minikube - local k8s
 - features - release notes

It's not the MOST simple, but I love that there is a repo called kubernetes, makes it clear where to file tickets and look at.

**Comment by petey** [comment]
Addressed in PR #20
