### ISSUE TITLE
Communication Channels

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/guide#14]
We should publish where we look for: 
 - questions
 - feature requests
 - bugs
 - generic chat

Inspiration: http://kubernetes.io/docs/troubleshooting/

**Comment by nicolaifsf** [comment]
Feature requests, questions, and bugs could perhaps all be on a single repo, perhaps the guide repository?
Then for generic chat, maybe we can use something similar to https://rocket.chat/ ?

**Comment by stjohnjohnson** [comment]
Spinnaker also has a similar approach http://www.spinnaker.io/docs/support-policy
 - Slack
 - Stackoverflow
 - Issues

Maybe we should rename api into "screwdriver-cd" and just use that for all the issue tracking.

**Comment by stjohnjohnson** [comment]
Created a slack channel `screwdriver-cd.slack.com`
