### ISSUE TITLE
Under "Deploy Screwdriver", Screwdriver API repo does not have kubernetes directory

### ISSUE THREAD

**Issue by bdangit** [screwdriver-cd/guide#35]
I'm trying to deploy SD into K8s, but I don't know what exactly I need to deploy.  It would help if you can share the service.yaml and deployment.yaml.

**Comment by stjohnjohnson** [comment]
Ahh, good catch.  We moved our k8s configuration under a separate repository: https://github.com/screwdriver-cd/kubernetes

We'll update the docs.

We are planning to build an all-in-one bootstrap command to get started quickly (similar to how k8s has their setup).

**Comment by bdangit** [comment]
Lgtm! :thumbsup:

Ref: https://github.com/screwdriver-cd/kubernetes

**Comment by bdangit** [comment]
Thanks all!
